base:
  project: gnn-adversarial-regularization
  random_state: 200
  
data_source:
  dataset: Dataset

load_data:
  raw_dataset: data/raw/Dataset

split_data:
  train_path: data/processed/train
  test_path: data/processed/test
  test_size: 0.2

model_dir: saved_models