base:
  project: gnn-adversarial-regularization
  random_state: 200
  
data_source:
  dataset1: Dataset
  dataset2: train
  dataset3: test

load_data:
  raw_dataset1: data
  raw_dataset2: raw

split_data:
  train_path1: data
  train_path2: processed
  train_path3: train
  test_path1: data
  test_path2: processed
  test_path3: test
  test_size: 0.25

model_dir: saved_models